src/components/EnchantBanner/index.tsx, src/pages/enchant/index.tsx
- add: enchant discontinued
- remove: toggleWallet
=> add: EnchantBanner

src/pages/scarab/index.tsx
- fix style table: scarab
- set: default scarab
=> add: Approve to Scarab

locale/de.po, locale/en.po, locale/es-AR.po, locale/es.po, locale/fr.po, locale/it.po, locale/ja.po, locale/ko.po, locale/ro.po, locale/ru.po, locale/vi.po, locale/zh-CN.po, locale/zh-TW.po, src/components/Title/index.tsx, src/pages/exchange/pool/index.tsx, src/pages/exchange/swap/[[...tokens]].tsx, src/sdk/entities/NativeCurrency.ts
- fix: img error
- update swap: add currency check for FTM to avoid errors.
=> add: Kek Chart, update alert: Pools

src/components/Header/index.tsx, src/components/TokenStats/index.tsx, src/constants/addresses.ts, src/constants/tokens/index.ts, src/features/summoner/hooks.ts, src/hooks/useContract.ts, src/modals/TokenStatsModal/Option.tsx, src/modals/TokenStatsModal/PendingView.tsx, src/modals/TokenStatsModal/Standalone.tsx, src/modals/TokenStatsModal/index.tsx, src/pages/exchange/swap/[[...tokens]].tsx, src/state/application/hooks.ts
- include: Supply & Market Cap
- add: SOUL to wallet from Modal
=> add: SOUL Stats Modal

src/features/farm/FarmList.tsx, src/features/farm/Header.tsx
=> add searchbox to the farms

.gitignore, next.config.js, src/components/Header/index.tsx, src/modals/TokenStatsModal/index.tsx, src/pages/vote/index.tsx
=> add: feedback form to vote page

src/components/Header/index.tsx, src/pages/inactive.tsx
Feel free to ping me with any modification you seem fit =)
=> Add inactive page with links to enchant staking, circles and enchant liquidity removal

src/components/Header/index.tsx, src/constants/farms.ts, src/features/farm/Pids.ts, src/features/swap/MainHeader.tsx, src/pages/bridge/index.tsx, src/pages/exchange/pool/index.tsx, src/pages/info/index.tsx
=> update: headers

src/components/Header/index.tsx, src/pages/exchange/pool/index.tsx
=> update: Liquidity Positiioons button

src/features/trade/HeaderV1.tsx, src/pages/exchange/swap/[[...tokens]].tsx
=> fix: enable slippage controls

src/features/bond/BondRowRender.jsx
=> add to bonds: YTD and DAILY ROI

.gitignore, src/pages/exchange/pool/index.tsx, src/pages/exchange/swap/[[...tokens]].tsx
=> make: social link into buttons

src/pages/bridge/index.tsx, src/pages/exchange/swap/[[...tokens]].tsx
=> darken: bridge bg

src/components/Header/index.tsx, src/config/index.ts, src/config/routing.ts, src/config/wallet.ts, src/connectors/index.ts, src/constants/routing.ts, src/entities/FortmaticConnector.ts, src/features/lending/context.tsx, src/features/swap/ConfirmSwapModal.tsx, src/hooks/useLPTokensState.ts, src/pages/exchange/migrate/index.tsx, src/services/graph/fetchers/blocks.ts, src/services/graph/fetchers/masterchef.ts, src/state/swap/hooks.ts, src/theme/index.tsx
- make: FANTOM defaultChainId
- update: useLPTokensState
=> update: network connect settings, interval

src/components/Header/index.tsx, src/components/LuxorStats/index.tsx
- fix: wLUM.png (casing)
- fix: error on disconnected page
=> update: Header

src/components/YieldDetails/index.tsx, src/modals/LuxorStatsModal/index.tsx
=> SOUL per $1K

src/features/mines/utils/ManageBar.tsx
=> fix staking

src/components/Header/Mobile.tsx, src/components/Header/index.tsx, src/components/Header/useMobileMenu.tsx, src/features/mines/MineListItemDetails.tsx, src/features/mines/components/MineMenu.tsx
=> revert: header

src/modals/LuxorStatsModal/index.tsx, src/modals/TokensStatsModal/index.tsx, src/pages/exchange/swap/[[...tokens]].tsx, src/pages/seance/index.tsx
- Approve Button (swap) Color
- Token Module Logo Sizes
=> fix: MAX seance withdrawal

src/features/lending/actions/Borrow.tsx, src/features/lending/actions/Repay.tsx, src/layouts/Underworld/index.tsx, src/pages/borrow/index.tsx
- enable: Borrow on Demand (without adding more)
=> add [borrow]: Health, hide: Limit Rev, New Input

src/config/features.ts, src/enums/Feature.ts, src/layouts/SwapLayout.tsx, src/pages/bonds/all.tsx, src/pages/bonds/index.tsx, src/services/graph/fetchers/exchange.ts, src/services/graph/queries/masterchef.ts
=> fix: Swap Layout

locale/de.po, locale/en.po, locale/es-AR.po, locale/es.po, locale/fr.po, locale/it.po, locale/ja.po, locale/ko.po, locale/ro.po, locale/ru.po, locale/vi.po, locale/zh-CN.po, locale/zh-TW.po, src/constants/farms.ts, src/features/lending/actions/Borrow.tsx, src/hooks/usePrice.ts, src/pages/mines/index.tsx, yarn.lock
=> add: lending farms (wftm/eth, dai/eth)

src/components/AssetInput/index.tsx, src/components/BondsBanner/index.tsx, src/components/EnchantBanner/index.tsx, src/constants/farms.ts, src/features/mines/MineList.tsx, src/features/mines/MineListItem.tsx, src/features/mines/MineListItemDetails.tsx, src/features/mines/components/InformationDisclosure.tsx, src/features/mines/components/InvestmentDetails.tsx, src/features/mines/utils/ManageBar.tsx, src/pages/mines/index.tsx
- update farms: how-to
- update: mines TVL
- fix: tokenPrice
=> fix: farms

src/features/mines/MineListItem.tsx, src/features/mines/utils/ManageBar.tsx
=> update: logos

locale/de.po, locale/en.po, locale/es-AR.po, locale/es.po, locale/fr.po, locale/it.po, locale/ja.po, locale/ko.po, locale/ro.po, locale/ru.po, locale/vi.po, locale/zh-CN.po, locale/zh-TW.po, src/constants/farms.ts, src/features/trade/HeaderNew.tsx, src/pages/margin/index.tsx
- important: lowercase address added to farms
=> replace Limit with: Margin

src/constants/abis/spookyswap-factory.json, src/constants/farms.ts, src/features/migration/LPToken.ts, src/features/migration/index.ts, src/features/migration/useLPTokensState.ts, src/features/migration/useMigrateState.ts, src/features/migration/useSoulSwap.ts, src/features/mines/MineListItem.tsx, src/hooks/useContract.ts, src/pages/exchange/migrate/index.tsx
=> add: BNB lending farm

src/features/trade/HeaderNew.tsx
=> update: Swap Header

src/components/Header/useBar.tsx, src/features/autostake/AutostakeRowRender.tsx
- [fix: Autostake balance](https://github.com/SoulSwapFinance/soul-interface/commit/0ab4a0ae821496f892322d9004e29de8c15dab6d)[](https://github.com/BunsDev)
=> update: siderbar, fix: autostake balance

src/components/Header/NavigationItem.tsx, src/components/Header/styles.ts, src/components/Web3Status/index.tsx
=> fix: nav items

src/features/luxor/Bonds.ts, src/features/luxor/LuxorKey.jsx, src/features/luxor/LuxorRowRender.tsx, src/features/luxor/ModalKey.jsx, src/features/luxor/ModalRowRender.tsx
- enable Payout
- replace: Open with Payout
=> update: Luxor Bonds

src/features/luxor/Bonds.ts, src/hooks/useAPI.ts, src/pages/lend/[pair].tsx
=> revert lend

src/components/Header/More.tsx, src/components/Header/useBar.tsx, src/components/Header/useMobileMenu.tsx, src/components/HeaderV1/More.tsx, src/modals/LuxorStatsModal/index.tsx, src/modals/TokensStatsModal/index.tsx, src/pages/luxor/dashboard/index.tsx, src/pages/soul/dashboard/index.tsx
update: headers + token modals
=> update: Overviews + LUX Backing Price

src/features/crosschain/components/TokenSelect.tsx, src/features/crosschain/helpers/Chains.ts, src/features/crosschain/helpers/SwitchNetwork.ts, src/pages/luxor/dashboard/index.tsx, src/pages/soul/dashboard/index.tsx, src/pages/summoner/index.tsx
**update**: margins on Dashboards
=> add to farms: Staked, Claim, TVL

src/constants/token-lists/soulswap.tokenlist.json, src/features/summoner/Pools.ts
remove/unlist: REAPER, UNIDX, FUSDT from default token list
=> remove: retired smol farms

src/features/cross/crossStyles.tsx, src/pages/bridge/components/InputCurrencyBox.tsx, src/pages/cross/index.tsx, yarn.lock
- [update [cross]: Select Token](https://github.com/SoulSwapFinance/soul-interface/commit/401a6424c9d199b04a5f538af65c676d35f04445)
- [update: selectors, summary and enable: red delta](https://github.com/SoulSwapFinance/soul-interface/commit/2eb537d8f7e543a8019b2eaa25d1ada03e47ca7f)
=> enable [cross]: show chains, tokens (WIP)

src/features/summoner/Row.tsx
- Make more accurate (no more false positives)
=> fix: Withdraw Fee

src/components/Header/Desktop.tsx, src/components/Header/Mobile.tsx, src/components/Header/NavigationItem.tsx, src/components/Header/useMenu.tsx, src/components/TokenStats/index.tsx, src/features/bond/List.tsx, src/pages/bridge/index.tsx, src/pages/exchange/add/[[...tokens]].tsx, src/pages/exchange/aggregator/[[...tokens]].tsx, src/pages/exchange/cross/index.tsx, src/pages/exchange/pool/index.tsx, src/pages/exchange/remove/[[...tokens]].tsx, src/pages/exchange/swap/[[...tokens]].tsx, src/pages/exchange/swap/limit/[[...tokens]].tsx, src/pages/soul/autostake/index.tsx, src/pages/soul/dashboard/index.tsx, src/pages/summoner/index.tsx
add: Text to Large Banner, fix: Wallet
=> fix: TokenStats Placement, update: Banners

src/pages/bridge/index.tsx
:black_flag:‍:skull_and_crossbones:
=> remove: yar, lulz

src/components/Banner/index.tsx, src/features/lending/actions/Withdraw.tsx, src/features/summoner/List.tsx, src/features/summoner/Pools.ts, src/features/summoner/Row.tsx
- [limited warning and lend prompt on inactive](https://github.com/SoulSwapFinance/soul-interface/commit/665e94ee803e3944ebcb4d84056a5efe398820a2)
- [new Underworld Farms](https://github.com/SoulSwapFinance/soul-interface/commit/e968a90f6e26969b337cdfd4629c03b904d95eab)
=> update: Retired Pools

src/components/Banner/index.tsx, src/features/swap/SwapDropdown.tsx, src/pages/bridge/index.tsx, src/pages/exchange/add/[[...tokens]].tsx, src/pages/exchange/aggregator/[[...tokens]].tsx, src/pages/exchange/cross/index.tsx, src/pages/exchange/remove/[[...tokens]].tsx, src/pages/exchange/swap/[[...tokens]].tsx, src/pages/exchange/swap/limit/[[...tokens]].tsx, src/pages/luxor/bonds/index.tsx
=> +: Donate Banner, fix: Use Aggregator Path
